### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by Mattze96** [luckydonald/pytg#2]
When i start pytg my cpu core gets to 100%, is this normal?

**Comment by avinassh** [comment]
My CPU usage is also insane :/

**Comment by luckydonald** [comment]
Have a look in the Update, #19

**Comment by luckydonald** [comment]
This should be resolved by the update.

**Comment by avinassh** [comment]
@luckydonald may I know where was the problem? Beginner here, I can learn a thing or two :smiley:

**Comment by luckydonald** [comment]
The Method used. Back in the days the interaction with the telegram-cli was done by reading and writing the stdin and stdout, same as you would do by yourself.
To get new messages we had to ```.poll()``` the process.
Works a bit like 

> Hey do you have new output.    

This was done in a loop. 

> Hey, hey, hey, hey,hey,hey,hey,....

As you can figure, because it is always doing something (checking for output), the CPU was at 99%

The first "fix" was to just add a delay, so the CPU can do stuff between that.

The second one above, by @dirtyharry123, use a select to only check the input if there is new one, which magically needed less cpu. (I never used it, and don't fully understand it. I guess because the OS now did check that for you, it needed less CPU?) (Seriously I have no Idea. The key seems to be using [pythons ```select```](https://docs.python.org/2/library/select.html) which uses/wraps the [native ```select``` of the OS](http://linux.die.net/man/2/select).)

Since Version 0.3.0 (which was in the pytg2 fork, and probably unnoticed here) I started using sockets (the things with ports). They have the great ability to *block* until new input is available. Way better than *active waiting*, which we did with ```poll()``` before.
So, if there is no input, nothing happens, the CPU knows that, and can work on different things.
If there are no messages incoming, we use 0% CPU. Hooray!

This needed of course a socket in telegram, and modified the CLI. To make merging updates from the original CLI easier, I decided to just replace the lua interface to send the messages as json to pytg's socket. (see [telejson cli](https://github.com/luckydonald/telejson)). Since vysheng's CLI version 1.3.0, he has added json himself, replacing the need for my modification (sad face).

**tl;nr:**
Instead of [Busy waiting](http://en.wikipedia.org/wiki/Busy_waiting),
 [Blocking](http://en.wikipedia.org/wiki/Blocking_%28computing%29) is more efficient.

**Comment by avinassh** [comment]
Makes sense now! Thank you very much :beer: :+1:
