### ISSUE TITLE
Rich link previews are not working

### ISSUE THREAD

**Issue by ghost** [luckydonald/pytg#43]
When sending a link in a message, rich link previews are not working.
Sending a link normally on telegram-cli shows the rich link preview on the receivers client.

**Comment by luckydonald** [comment]
If I understand correctly, your link has no preview when sending with pytg?
Each function has a ```enable_preview``` kwarg you can either set to ```True``` or ```False```. It defaults to ```False```.
>More information can be found if you use ```help( )``` on the function you want to use, or by looking at the documentation of the ```execute_function()``` function in [sender.py, line 205 (currently commit d5135efdb5)](https://github.com/luckydonald/pytg/blob/d5135efdb5d80380370f0ef58b1492751574d751/pytg/sender.py#L205). There you can see which arguments are shared by all the cli related functions of pytg.sender.

Addressing your problem specifically, I am guessing you used ```.msg()``` (```.send_msg()``` or ```.send_text()``` are just alias, and doing the same). Please send me your code otherwise.

```python
# s is your sender instance,
# receiver is your receiver.
s.send_msg(receiver, "Some message with link to https://github.com/luckydonald/pytg/issues/43", enable_preview=True)
```
Tell me your code, and I can help you further.

**Comment by luckydonald** [comment]
This should be fixed. If this problem still exists please reopen.
